---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# verifier:
#   name: rspec

platforms:
  - name: ubuntu-16.04
    driver:
        network:
            - ["forwarded_port", {
                guest: 8080,
                host: 8080
            }]

suites:
  - name: default
    run_list:
      - recipe[jenkins_ubuntu::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
